datadump.location:
  author: /../././Authors_dump.txt
  works: /../././Works_dump.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: testusername
      password: testpassword
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: astra db id
  region: europe-west1
  keyspace: main
  application.token: AstraCS:app token








